### ISSUE TITLE
Thanks for your great work, and when will you release the code?

### ISSUE THREAD

**Issue by drilistbox** [reachpranjal/lego-drive#1]

**Comment by reachpranjal** [comment]
Thanks you for your interest. The work is currently in review for publication and will be released post-review.

**Comment by reachpranjal** [comment]
Thank you for your interest. The work is currently in review for publication and will be released post-review.

**Comment by wang123yuan** [comment]
Thanks for your great work, and when will you release the code?

**Comment by reachpranjal** [comment]
@wang123yuan Hi, we're updating our codebase for real-world deployment and integrating large vision-language models for upcoming submissions. Please expect some delay in the release.
